//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClient.TCPService5 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TCPService5.IService5", CallbackContract=typeof(WebClient.TCPService5.IService5Callback))]
    public interface IService5 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService5/DoWork", ReplyAction="http://tempuri.org/IService5/DoWorkResponse")]
        void DoWork(string inputString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService5/DoWork", ReplyAction="http://tempuri.org/IService5/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync(string inputString);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService5Callback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService5/OnCallBack")]
        void OnCallBack(string inputString);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService5Channel : WebClient.TCPService5.IService5, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service5Client : System.ServiceModel.DuplexClientBase<WebClient.TCPService5.IService5>, WebClient.TCPService5.IService5 {
        
        public Service5Client(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public Service5Client(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public Service5Client(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public Service5Client(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public Service5Client(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void DoWork(string inputString) {
            base.Channel.DoWork(inputString);
        }
        
        public System.Threading.Tasks.Task DoWorkAsync(string inputString) {
            return base.Channel.DoWorkAsync(inputString);
        }
    }
}
