//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClient.TcpService7 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class Student : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebClient.TcpService7.JuniorHighStudent))]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JuniorHighStudent", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class JuniorHighStudent : WebClient.TcpService7.Person {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Age1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Name1Field;
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="Age")]
        public int Age1 {
            get {
                return this.Age1Field;
            }
            set {
                if ((this.Age1Field.Equals(value) != true)) {
                    this.Age1Field = value;
                    this.RaisePropertyChanged("Age1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="Name")]
        public string Name1 {
            get {
                return this.Name1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Name1Field, value) != true)) {
                    this.Name1Field = value;
                    this.RaisePropertyChanged("Name1");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="Chiupin.Chen.Com", ConfigurationName="TcpService7.IService7")]
    public interface IService7 {
        
        [System.ServiceModel.OperationContractAttribute(Action="Chiupin.Chen.Com/IService7/DoWork", ReplyAction="Chiupin.Chen.Com/IService7/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="Chiupin.Chen.Com/IService7/DoWork", ReplyAction="Chiupin.Chen.Com/IService7/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="Chiupin.Chen.Com/IService7/GetStudent", ReplyAction="Chiupin.Chen.Com/IService7/GetStudentResponse")]
        WebClient.TcpService7.Student GetStudent();
        
        [System.ServiceModel.OperationContractAttribute(Action="Chiupin.Chen.Com/IService7/GetStudent", ReplyAction="Chiupin.Chen.Com/IService7/GetStudentResponse")]
        System.Threading.Tasks.Task<WebClient.TcpService7.Student> GetStudentAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="Chiupin.Chen.Com/IService7/GetJuniorHighStudent", ReplyAction="Chiupin.Chen.Com/IService7/GetJuniorHighStudentResponse")]
        WebClient.TcpService7.Person GetJuniorHighStudent(WebClient.TcpService7.Person juniorHighStudent);
        
        [System.ServiceModel.OperationContractAttribute(Action="Chiupin.Chen.Com/IService7/GetJuniorHighStudent", ReplyAction="Chiupin.Chen.Com/IService7/GetJuniorHighStudentResponse")]
        System.Threading.Tasks.Task<WebClient.TcpService7.Person> GetJuniorHighStudentAsync(WebClient.TcpService7.Person juniorHighStudent);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService7Channel : WebClient.TcpService7.IService7, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service7Client : System.ServiceModel.ClientBase<WebClient.TcpService7.IService7>, WebClient.TcpService7.IService7 {
        
        public Service7Client() {
        }
        
        public Service7Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service7Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service7Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service7Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public WebClient.TcpService7.Student GetStudent() {
            return base.Channel.GetStudent();
        }
        
        public System.Threading.Tasks.Task<WebClient.TcpService7.Student> GetStudentAsync() {
            return base.Channel.GetStudentAsync();
        }
        
        public WebClient.TcpService7.Person GetJuniorHighStudent(WebClient.TcpService7.Person juniorHighStudent) {
            return base.Channel.GetJuniorHighStudent(juniorHighStudent);
        }
        
        public System.Threading.Tasks.Task<WebClient.TcpService7.Person> GetJuniorHighStudentAsync(WebClient.TcpService7.Person juniorHighStudent) {
            return base.Channel.GetJuniorHighStudentAsync(juniorHighStudent);
        }
    }
}
