//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClient.TCPService6 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TCPService6.IService6")]
    public interface IService6 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService6/DoWork", ReplyAction="http://tempuri.org/IService6/DoWorkResponse")]
        int DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService6/DoWork", ReplyAction="http://tempuri.org/IService6/DoWorkResponse")]
        System.Threading.Tasks.Task<int> DoWorkAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService6Channel : WebClient.TCPService6.IService6, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service6Client : System.ServiceModel.ClientBase<WebClient.TCPService6.IService6>, WebClient.TCPService6.IService6 {
        
        public Service6Client() {
        }
        
        public Service6Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service6Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service6Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service6Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int DoWork() {
            return base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task<int> DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
    }
}
